// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  materiasSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Introducción",
    },
    {
      type: "category",
      label: "Materias",
      items: [
        {
          type: "autogenerated",
          dirName: "materias",
        },
      ],
    },
  ],
};
