import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  materiasSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Introducción",
    },
    {
      type: "category",
      label: "Materias",
      collapsed: true, // Ahora es colapsable/ocultable
      collapsible: true,
      items: [
        {
          type: "autogenerated",
          dirName: "materias",
        },
      ],
    },
    {
      type: "category",
      label: "Referencias",
      collapsed: true,
      collapsible: true,
      items: [
        {
          type: "autogenerated",
          dirName: "referencias",
        },
      ],
    },
  ],
};

export default sidebars;
